config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => { :sign_up => "register", :sign_in => "login"}
  resources :products do 
    member do
       get :share_product
       post :check_product_shared_or_not 
    end
  end

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  ##################
  ## Associations
  ################        
  belongs_to :user
  has_and_belongs_to_many :users
  
  #######################
  ## Attribute Accessors
  #######################
  ###############
  ## Validations
  ###############
  validates :name, :description, presence: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ##################
  ## Associations
  ################        
  has_many :products
  has_and_belongs_to_many :products
  
  ###############
  ## Validations
  ###############
  validates :username,
    :presence => true,
    :uniqueness => {
      :case_sensitive => false
    }
  
  ##############
  ## Call Backs
  ##############
  
  #################
  ## Class Methods
  #################
  class << self
  
  end
  
  ######################
  ## Virtual Attributes
  ######################
  attr_accessor :login
  
  ##################
  ## Public Methods
  ##################
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions.to_hash).first
    end
  end
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :get_shared_product_of_current_user

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
  
  def get_shared_product_of_current_user
    @shared_products = current_user.products if current_user
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def check_product_shared_or_not
    hash = {}
    user = User.where(id: params[:user_id]).first
    hash["#{user.id}"] = "user_id"
    if user.products.collect {|x| x.id }.include? params[:id].to_i
      hash[:already_shared] = "already_shared"
      render json: hash
    else
      hash[:share] = "can_share"
      render json: hash
    end
    #redirect_to request.referer
  end
  
  def share_product
    #save records in third table
    user = User.where(id: params[:user_id]).first
    product = Product.where(id: params[:id]).first
    user.products << product
    flash[:notice] = "Product has been shared with #{user.username}."
    redirect_to request.referer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def user_list
    return User.all.collect {|x| [x.username, x.id] if x.id != current_user.id }.compact
  end

  def get_owner(product)
    if product.user.present?
      return product.user.username
    else
      return "Owner has been deleted"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp1</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path, class: "btn"%></li>
        <li><%= link_to "About Us", root_path %></li>
        <li><%= link_to "Contact", root_path %></li>
        <% if current_user %>
          <li><%= link_to "Shared Product list", "#", onclick: "dialog_div_for_shared_products(\"shared_product\", 520); return false;", id: "link_shared_product", :title => "Click to view the product list which was shared with other users to current user." %></li>
        <% end %>  
        <% if user_signed_in? %>
          <li style="float: right;"><%= link_to "Sign Out", destroy_user_session_path, method: :DELETE %></li>
          <li style="float: right; margin-top: 12px;"><%= "Signed in as #{current_user.username}." %> </li>
        <% else %>
          <li style="float: right;"><%= link_to "Sign up", new_user_registration_path %></li>
          <li style="float: right;"><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
      <br>
      <% if notice %>
        <p style="text-align: center; font-size: 17px;" class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p style="text-align: center; font-size: 17px;" class="alert alert-danger"><%= alert %></p>
      <% end %>
      <% if current_user %>
        <%= render 'products/shared_product_list' %>
      <% end %>  
      <%= yield %>
       
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: 'Enter the product name', required: 'true', style: 'width: 50%;' %>
    <% if @product.errors.present? and @product.errors.messages[:name].present? %>
      <div style="color: red;"><%= @product.errors.messages[:name].join %></div>
    <% end %>
  </div>
  <br>
  <div>
    <%= f.label :description %> 
    <%= f.text_area :description, class: "form-control", placeholder: 'Enter the product description', required: 'true', style: 'width: 50%;' %>
    <% if @product.errors.present? and @product.errors.messages[:description].present? %>
      <div style="color:red;"><%= @product.errors.messages[:description].join %></div>
    <% end %>
  </div>
  </br>
  <div>
    <%= f.submit class: "btn btn-primary" %> &nbsp;&nbsp;&nbsp;
    <%= link_to 'Back', products_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/_share_product.html.haml
.popup_dialog_div.share_product_box{title: "Share Product", id: 'share_product_' + share_product.id.to_s}
  #share_div
    .btn-group
      = form_tag check_product_shared_or_not_product_path(share_product.id), id: "share_form_#{share_product.id}" do
        %table.form-table{style: "margin-bottom:0px !important; "}
          %tr{style: "float: left; margin-top: 20px;"}
            %th= label_tag "Register Users"
            %td 
              &nbsp; &nbsp;
              = select_tag "user_id", options_for_select(user_list), prompt: "Please Select the User", style: "width: 240px;", required: 'true'
          %tr{style: "margin-top: -5px; float: left; margin-left:40px;"}
            %td
              %br
              = submit_tag "Ok", class: 'btn btn-primary', onclick: "check_product_already_shared_or_not('#{share_product.id}');" 
          %tr{style: "display: none", id: "error_div_#{share_product.id}"}
            %td{style:"color: red;"}
              = "Product: #{share_product.name} has been already shared with selected user. Please select the other one"    

app/views/products/_shared_product_list.html.haml
.popup_dialog_div.shared_product_box{title: "Share Product", id: 'shared_product'}
  #share_div
    %table{class: "table table-striped"}
      %thead 
        %tr
          %th 
            = "Name" 
          %th
            = "Description"
          %th
            = "Product Owner"   
      %tbody 
        - @shared_products.each do |shared_product| 
          %tr
            %td 
              = shared_product.name  
            %td
              = shared_product.description  
            %td
              = get_owner(shared_product)
         

app/views/products/edit.html.erb
<div class="form-group">
  <%= render 'form' %>
</div>  

app/views/products/index.html.erb
<% if @products.present? %>
  <div class="box1">
    <table class="table table-striped">
      <thead>
        <tr style= "background-color: #e2e7ff">
          <th>Name</th>
          <th>Description</th>
          <th class="col-xs-1">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td style="width: 19%;">
              <%= link_to 'Show', product, title: 'click to show the product' %> &nbsp;&nbsp;&nbsp;
              <%= link_to 'Edit', edit_product_path(product), title: 'click to edit the product' %>&nbsp;&nbsp;&nbsp; 
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, title: 'click to delete the product' %>&nbsp;&nbsp;&nbsp;
              <%= link_to 'Share', "#", onclick: "show_popup_dialog_div(\"share_product_#{product.id}\", 520); return false;", id: "link_share_product_#{product.id}", :title => "Click to share the product with other registered users." %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>  
<%= render partial: 'products/share_product', :collection => @products %>  
<% else %>
  <h3> No Product created yet.</h3>
<% end %>
<br>   
<%= link_to 'New Product', new_product_path, class: 'btn btn-primary', title: 'click to create a new product' %>

app/views/products/new.html.erb
<div class="form-group">
  <%= render 'form' %>
</div>  

app/views/products/show.html.erb
<div class="box1"> 
  </br>
  <div>
    <strong>Name:</strong>
    <%= @product.name %>
  </div>
  <div>
    <strong>Description:</strong>
    <%= @product.description %>
  </div>
  </br>
  <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary' %> 
  <%= link_to 'Back', products_path, class: 'btn btn-primary' %>
</div>  

app/views/users/shared/_links.html.erb
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>